server:
  port: 8089
spring:
  application:
    name: api-keycloak-admin

  datasource:
    url: jdbc:mysql://localhost:3310/user_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: 'admin1234'
    password: "admin1234"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus","health", "info" ]
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    tags:
      application: ${spring.application.name}
      service: api-product
      environment: dev

logging:
  file:
    name: ../shared-logs/${spring.application.name}.log
  level:
    root: INFO
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring.security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8080/realms/saas-application/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8080
  realm: saas-application
  client-id: backend-keycloak
  client-secret: RQ6XrKzEG5OGlgnJ9Yy4jktWXO5BVauU


custom:
  pageSize: 30
  clients:
    - react-client
    - backend-keycloak
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka