server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api-product
    static_configs:
      - targets: [ 'localhost' ]
        labels:
          job: api-product
          __path__: /shared-logs/product-service.log
  - job_name: keycloak-admin
    static_configs:
      - targets: [ 'localhost' ]
        labels:
          job: "keycloak-admin"
          __path__: /shared-logs/keycloak-admin.log