services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: ${mysql_keycloak_db}
      KC_DB_USERNAME: ${mysql_keycloak_user}
      KC_DB_PASSWORD: ${mysql_keycloak_password}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8070/health/ready || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s
    command: ["start-dev","--import-realm"]
    ports:
      - "${keycloak_port}"
    networks:
      - backend-network
    volumes:
    - ../../:/opt/keycloak/data/import


networks:
  backend-network:
    name: backend-network
    driver: bridge