server:
  port: 8087
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3311/product_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: 'admin1234'
    password: 'admin1234'
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus","health", "info" ]
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    tags:
      application: ${spring.application.name}
      service: api-product
      environment: dev



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: shared-logs/${spring.application.name}.log
  level:
    root: INFO
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'